name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  load-manifest:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.detect-matrix.outputs.variants }}
    steps:
      - uses: actions/checkout@v2
      - name: Detect Matrix
        id: detect-matrix
        run: |
          $manifest = Get-Content ./manifest.json | ConvertFrom-Json
          $variants = @()
          foreach ($property in $manifest.PSObject.Properties) {
              $value = $property.Value
              $variants += @{
                "type" = $property.Name
                "version" = $value.version
                "docker-file" = $value.dockerFile
                "context" = $value.context
                "image-name-suffix" = $value.imageNameSuffix
              }
          }
          $json = ConvertTo-Json -Compress $variants
          Write-Host "::set-output name=variants::$json"
        shell: pwsh
  build:
    needs:
      - load-manifest
    strategy:
      matrix:
        variants: ${{ fromJSON(needs.load-manifest.outputs.variants) }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMES: |
        contrastdotnet.azurecr.io/agent-operator/agents/${{ matrix.variants.image-name-suffix }}
      CACHED_IMAGE_NAME: contrastdotnet.azurecr.io/agent-operator/cache/${{ matrix.variants.image-name-suffix }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE_NAMES }}
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.variants.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.variants.version }}
            type=semver,pattern={{major}},value=${{ matrix.variants.version }}

            type=match,pattern=(\d+\.\d+\.\d+\.\d+),group=1,value=${{ matrix.variants.version }},enable=${{ matrix.variants.type == 'java' }}
            type=match,pattern=(\d+\.\d+\.\d+)\.\d+,group=1,value=${{ matrix.variants.version }},enable=${{ matrix.variants.type == 'java' }}
            type=match,pattern=(\d+\.\d+)\.\d+\.\d+,group=1,value=${{ matrix.variants.version }},enable=${{ matrix.variants.type == 'java' }}
            type=match,pattern=(\d+)\.\d+\.\d+\.\d+,group=1,value=${{ matrix.variants.version }},enable=${{ matrix.variants.type == 'java' }}

            type=raw,value=${{ matrix.variants.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: contrastdotnet.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.variants.docker-file }}
          context: ${{ matrix.variants.context }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: ${{ env.CACHED_IMAGE_NAME }}:latest
          cache-to: ${{ env.CACHED_IMAGE_NAME }}:latest
          build-args: |
            VERSION=${{ matrix.variants.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
